name: Update the docs
on: [push, workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        curl https://raw.githubusercontent.com/curbengh/urlhaus-filter/master/urlhaus-filter-domains.txt -o urlhaus.txt
    - uses: EndBug/add-and-commit@v7.2.1
      with:
        author_name: iam-py-test
        author_email: 84232764+iam-py-test@users.noreply.github.com
        message: '[bot] Update offline assets'
    
