name: Update the docs
on: [push, workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Build
      run: |
        echo test2 > "test.txt"
    - uses: EndBug/add-and-commit@v7.2.1
      with:
        author_name: iam-py-test
        author_email: 84232764+iam-py-test@users.noreply.github.com
        message: '[bot] Update offline assets'
    
